### ISSUE TITLE
We couldn't find that photo

### ISSUE THREAD

**Issue by fugazi** [evtn/splashpaper#3]
Splashpaper is not working anymore. The wallpaper doesn't update anymore in Windows. Please fix this. Thanks.
![image](https://user-images.githubusercontent.com/403366/231196465-2bcdc49b-d1db-4f38-9182-efbf49992dc5.png)

**Comment by evtn** [comment]
What's the request used?

**Comment by fugazi** [comment]
@evtn honestly, I don't know how to get that request used, because I just have taken a screenshot from my Windows PC.

**Comment by fugazi** [comment]
@evtn By the way, I am using the Splashpaper application from Microsoft Windows. Thanks

**Comment by evtn** [comment]
I can check the request if you provide the command you use to launch splashpaper.

But I see that if used without arguments (e.g. just `python -m splashpaper`), it produces the result you've shown. That's probably a change in Unsplash API, you can try providing some arguments (check out `python -m splashpaper` to see available options). 

I'm not actively supporting the package since Unsplash has made its API fully private, and it seems that it now works only to preserve backwards compatibility.

**Comment by fugazi** [comment]
@evtn Thanks for the information. But I am not using the splash paper python script. I just downloaded the Splashpaper application from Microsoft Store for Windows. https://apps.microsoft.com/store/detail/splashpaper/9NBLGGH5LD3C
I realized that Maarten Zuidhoorn is the guy behind the support.

No problem. Thanks a lot for the kind replies.

**Comment by evtn** [comment]
Glad to help, if you will decide to use the script, feel free to ask questions
